"""support_multiple_llm_configs

Revision ID: 5b0d2d3e48aa
Revises: 008
Create Date: 2026-05-10 21:51:44.310532
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b0d2d3e48aa'
down_revision: Union[str, None] = '008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add is_active column with default 0
    op.add_column('llm_configs', sa.Column('is_active', sa.Integer(), nullable=False, server_default='0'))


def downgrade() -> None:
    op.drop_column('llm_configs', 'is_active')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.create_index(op.f('idx_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('idx_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=False)
    op.drop_index(op.f('ix_rag_configs_user_id'), table_name='rag_configs')
    op.create_index(op.f('idx_rag_configs_user_id_unique'), 'rag_configs', ['user_id'], unique=1)
    op.create_index(op.f('idx_rag_configs_user_id'), 'rag_configs', ['user_id'], unique=False)
    op.drop_constraint('uq_user_provider', 'llm_configs', type_='unique')
    op.create_index(op.f('idx_llm_configs_user_id_unique'), 'llm_configs', ['user_id'], unique=1)
    op.create_index(op.f('idx_llm_configs_user_id'), 'llm_configs', ['user_id'], unique=False)
    op.alter_column('llm_configs', 'provider',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('llm_configs', 'is_active')
    op.drop_index(op.f('ix_embedding_configs_user_id'), table_name='embedding_configs')
    op.create_index(op.f('idx_embedding_configs_user_id_unique'), 'embedding_configs', ['user_id'], unique=1)
    op.create_index(op.f('idx_embedding_configs_user_id'), 'embedding_configs', ['user_id'], unique=False)
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_documents_view_count'), table_name='documents')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_last_viewed_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_is_favorite'), table_name='documents')
    op.drop_index(op.f('ix_documents_file_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_category'), table_name='documents')
    op.create_index(op.f('idx_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_index(op.f('idx_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('idx_documents_favorite'), 'documents', ['user_id', 'is_favorite'], unique=False)
    op.create_index(op.f('idx_documents_category'), 'documents', ['category'], unique=False)
    op.alter_column('documents', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.create_index(op.f('idx_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_index(op.f('idx_chat_sessions_updated_at'), 'chat_sessions', ['updated_at'], unique=False)
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.create_index(op.f('idx_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.alter_column('api_keys', 'key_prefix',
               existing_type=sa.String(length=11),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    op.drop_constraint(None, 'activity_log', type_='foreignkey')
    op.create_foreign_key(None, 'activity_log', 'documents', ['document_id'], ['id'])
    op.drop_index(op.f('ix_activity_log_user_id'), table_name='activity_log')
    op.drop_index(op.f('ix_activity_log_document_id'), table_name='activity_log')
    op.create_index(op.f('idx_activity_user_id'), 'activity_log', ['user_id'], unique=False)
    op.create_index(op.f('idx_activity_created_at'), 'activity_log', ['created_at'], unique=False)
    op.alter_column('activity_log', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_table('documents_fts_idx',
    sa.Column('segid', sa.NullType(), nullable=False),
    sa.Column('term', sa.NullType(), nullable=False),
    sa.Column('pgno', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('segid', 'term')
    )
    op.create_table('documents_fts_config',
    sa.Column('k', sa.NullType(), nullable=False),
    sa.Column('v', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('k')
    )
    op.create_table('documents_fts',
    sa.Column('title', sa.NullType(), nullable=True),
    sa.Column('content_text', sa.NullType(), nullable=True)
    )
    op.create_table('documents_fts_data',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('block', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents_fts_docsize',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('sz', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
